#!/bin/bash
# Copyright 2007, 2008, 2011, 2012 by Kyle Sallee,
# All rights reserved.
# For use with the distribution Sorcerer only.
# boot-blaze accelerates booting

export LC_ALL=C

H=/var/log/boot-blaze

e(){ while read; [ -f "$REPLY" ] && echo -n "$REPLY "; done; }
l(){ [ -f $H ] && e < $H; }

if   [[ $HOSTTYPE == x86_64 ]]
then L=/lib64
else L=/lib
fi

main(){
 LD_PRELOAD="$( l )" /usr/bin/sleep 900

 cat /proc/*/maps |
 tr ' ' '\n' | 
 grep "$L/lib.*\.so\." |
 sort -u > $H
}

main &>/dev/null &
