#!/bin/bash

### BEGIN INIT INFO
# Provides: snmpd
# Required-Start: $network run
# Required-Stop: $network
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 6
# Short-Description: snmpd starts and stops the net-snmp SNMP daemon
### END INIT INFO

. /lib/lsb/init-functions

NAME="snmpd"
PROG="/usr/sbin/snmpd"
PIDF="/var/run/snmpd.pid"
OPTS='-r -u nobody'

parse
