#!/bin/bash
   VERSION=( "2.15" "2.14" )
  CATEGORY="development"
 ATTRIBUTE="core console solo"
    SOURCE="binutils/binutils-$VERSION.tar.bz2"
  HOMEPAGE="http://sources.redhat.com/binutils"
       URL="$GNU_URL"
   PROTECT="/usr/bin/as
            /usr/bin/ld
            /usr/bin/ranlib"
  ESTIMATE="587"
      DESC="binutils is an essential collection of binary utilities.

binutils - Collection of binary utilities
ld		-the GNU linker
as		-the portable GNU assembler
ar		-creates, modifies, and extracts from archives
nm		-lists symbols from object files
objcopy		-copies and translates object files
objdump		-displays information from object files
ranlib		-indexes the contents of an archive
size		-lists the section sizes of an object or archive file
strings		-lists printable strings from files
strip		-discards symbols
c++filt		-filter to demangle encoded C++ symbols
addr2line	-converts addresses to file and line
nlmconv		-converts object code into an NLM
"


build()  {

	
  export    CFLAGS="${CFLAGS/-fomit-frame-pointer/}"
  export  CXXFLAGS="${CXXFLAGS/-fomit-frame-pointer/}"

  LDF="LDFLAGS=$LDFLAGS"

	OPTS="$OPTS --host=$BUILD"
	if [ -n "$DEST_ARCH" ]; then
		OPTS="$OPTS --prefix=/opt/${DEST_ARCH}"
	else
		OPTS="$OPTS --prefix=/usr"
	fi
	echo OPTS=$OPTS
  echo DEST_ARCH=$DEST_ARCH

  ./configure    $OPTS        &&
  make          "$LDF"  $TD   &&
  prepare_install             &&
  make    install       $TD   &&
  make    install-info  $TD

}
