#!/bin/bash

if   read < /proc/cmdline;
     [[ $REPLY =~ boot=IR ]] &&
     ! grep -q /media/root /etc/fstab
then
 if   [[ $@ =~ tty1 ]] && [ -f /bin/login_root ]
 then exec  /sbin/agetty -n -l /bin/login_root "$@"
 else exec  /sbin/agetty "$@"
 fi
elif [ -x /media/root/etc/init.d/boot-sentient ] &&
     [ -f /media/root/bin/login_root ] &&
     [ -f /media/root/sbin/agetty ] &&
     [[ $@ =~ tty1 ]]
then exec /bin/chroot /media/root /sbin/agetty -n -l /bin/login_root "$@"
elif [ -f /media/root/sbin/agetty ]
then exec /bin/chroot /media/root /sbin/agetty "$@"
else                              /sbin/agetty "$@"
fi
