#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 510
# Required-Start: $network run
# Required-Stop: $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: nsdc provides the name server daemon control script
### END INIT INFO

. /lib/lsb/init-functions

only start stop restart try-restart status
pid_file /var/run/nsd.pid
server /usr/sbin/nsdc
config /etc/nsd.conf
options $1
