#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 500
# Required-Start: proc
# Default-Start: S
# Default-Stop 0 1 2 3 4 5 6
# Short-Description: allows person at keyboard to kill stalled init-scripts
### END INIT INFO

. /lib/lsb/init-functions

only start stop
server /sbin/boot-kick

stop(){ stops; setleds -L < /dev/console > /dev/null; return 0; }
