#!/bin/bash

### BEGIN INIT INFO
# Provides: agrmodem
# Required-Start: $local_fs
# Should-Start: udev
# Required-Stop:  $local_fs
# Default-Start: 2 3 4 5
# Default-Stop:
# Short-Description: agrmodem loads the module
# Description: agrmodem loads the module
### END INIT INFO

. /lib/lsb/init-functions

NAME=agrmodem

parse "$@"
