#!/bin/bash

### BEGIN INIT INFO
# Provides: kdm-v3
# Required-Start: $local_fs run ICE-unix
# Should-Start: $network $remote_fs udev xfs
# Required-Stop: kill
# Should-Stop: $remote_fs $network initramfs
# Default-Start: 4 5
# Default-Stop: 0 6
# Short-Description: kdm-v3 provides an x11 login.
# Description: kdm-v3 provides an x11 login.
### END INIT INFO

. /lib/lsb/init-functions

PIDF=/var/run/xdm.pid
SERV=/opt/kde3/bin/kdm
NAME=kdm
export PATH="/opt/kde3/bin:$PATH"

parse "$@"
