#!/bin/bash

### BEGIN INIT INFO
# Provides: fuse
# Required-Start: $local_fs
# Should-Start: udev
# Required-Stop: halt reboot
# Default-Start: S
# Default-Stop: 0 6
# Short-Description: fuse starts fuse at boot
# Description: fuse starts fuse at boot
#   Okay not the best init file.
#   I will improve it later.
### END INIT INFO

. /lib/lsb/init-functions


start()  {
  log_warning_msg  "fuse about to start"
  [  -f                /proc/mounts    ]  ||
  mount -nrt proc proc /proc
  modprobe fuse  &>/dev/null
  if    mount -t fusectl none /sys/fs/fuse/connections
  then  log_success_msg  "fuse started"
  else  log_failure_msg  "Unable to mount fuse control filesystem"
  fi
}

stop() {
  log_warning_msg  "fuse about to stop"
  if    grep  -qw  /sys/fs/fuse/connections  /proc/mounts  &&
        umount     /sys/fs/fuse/connections
  then  log_success_msg  "fuse stopped"
  else  log_failure_msg  "fuse not stopped"
  fi
}

help()  {  echo "Usage: $0 {start|stop}" 1>&2;  }

case  $1  in
  start)  start  ;;
   stop)  stop   ;;
      *)  help   ;;
esac
