#!/bin/bash
### BEGIN INIT INFO
# Default-Mode: 500
# Required-Stop: $local_fs
# Should-Stop: initramfs tmp
# Default-Stop: 0 6
# Short-Description: updates /usr/share/info/ based upon the content of /usr/share/info/.d/
### END INIT INFO

# Copyright 2013 by Kyle Sallee, all rights reserved.
# for use with Modern Magic only

i=/usr/share/info
d=$i/dir

[ -d $i ] || exit 0

. /lib/lsb/init-functions

only stop
deny control

check(){ ! [ -f $d ] || find $i -type f -newer $d | grep -q .; }

update(){
 rm   -f   $d
 find $i/ -type f -name \*.info |
 xargs -r -d '\n' -L1 -- install-info --dir-file=$d --quiet --
}

stop(){
 if   log_warning_msg "$d check"; check
 then log_warning_msg "$d update"; update
      log_success_msg "$d update"
 else log_success_msg "$d check"
 fi
}
