#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 500
# Required-Stop: $local_fs swap term tmp
# Default-Stop: 0 6
# Short-Description: issues kill signals to lingering processes
### END INIT INFO

. /lib/lsb/init-functions

only stop
deny control

flare(){
 log_warning_msg "$1 signal send"; /sbin/killall5 $2
 log_success_msg "$1 signal send"
}

stop(){
 if   rootfs
 then flare KILL  -9; /bin/sleep 0.1
 else flare TERM -15; /bin/sleep 0.1
 fi
}
