#!/bin/bash

# Copyright Kyle Sallee 2011, 2012
# All rights reserved.
# For use with the distribution sorcerer only!

### BEGIN INIT INFO
# Default-Mode: 500
# Required-Start: $local_fs
# Default-Start: S
# Short-Description: checks and sets symbolic link /etc/localtime
### END INIT INFO

# omit log

e=
for  d in /media/root/*; do
 if   [ -d   "$d"/usr/share/zoneinfo ]
 then        "$d" $0 "$@"; e=1
 fi
done
if [ -n "$e" ]; then exit 0; fi

. /lib/lsb/init-functions

only start reload status
config /usr/share/zoneinfo
name /etc/localtime

run(){

 tz_menulist(){ find $CONF -type f -printf '%P	Zone\n' | LC_ALL=C sort; }

 tz_menu(){
  BACKTITLE=$"Timezone Configuration Menu"
      TITLE=$"Timezone Selection"
       HELP=$"Please select the computer's location within 60 seconds."

  dialog \
   --backtitle "$BACKTITLE"  \
   --title     "$TITLE"      \
   --timeout 60              \
   --stdout --no-cancel      \
   --menu "$HELP" 0 0 0      \
   $( tz_menulist )
 }

 LOCALTIME="$( tz_menu )" && redraw
 if [ "$LOCALTIME" ]; then
  rm -f  $NAME
  ln -sv $CONF/$LOCALTIME $NAME
 fi
}

status(){
 symlinkedfile(){ [ -h $1 ] && [ -f $1 ]; }

 if   log_warning_msg "$NAME checking"; symlinkedfile $NAME
 then log_success_msg "$NAME checked"
 else log_warning_msg "$NAME missing"; return 1
 fi
}

start(){ if ! status ; then [ -d /usr/share/zoneinfo ] && run; fi; }
reload(){ rm -f $NAME; start; }
