#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 500
# Should-Start: proc
# Default-Start: S
# Short-Description: enables proxy_arp, necessary for veth
### END INIT INFO

. /lib/lsb/init-functions

only start stop status
config /proc/sys/net/ipv4/conf/all/proxy_arp

start(){
 if   log_warning_msg "proxy_arp enable"; echo 1 > /proc/sys/net/ipv4/conf/all/proxy_arp
 then log_success_msg "proxy_arp enable"
 else log_failure_msg "proxy_arp enable"; return 1
 fi
}

stop(){
 if   log_warning_msg "proxy_arp stop"; echo 0 > /proc/sys/net/ipv4/conf/all/proxy_arp
 then log_success_msg "proxy_arp stop"
 else log_failure_msg "proxy_arp stop"; return 1
 fi
}
