#!/bin/bash
# Copyright 2011 by Kyle Sallee
# All Rights Reserved
# For use on Sorcerer only

trap : INT QUIT TSTP
export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
umask 022

run(){
 if ! [ -f $1 ]; then return 1; fi
 if ! [ -x $1 ]; then return 1; fi
 $1 $2
}

series(){
 echo "Sysinit Begin"
 for S in /etc/rc.d/rcS.d/*; do run $S start; done
 echo "Sysinit End"
}

/sbin/agetty -f /etc/issue.rootfs /dev/tty7 9600 &

if   ! [    -f               /proc/mounts ] ||
     ! grep -q /var/log/init /proc/mounts; then
 mkdir -pm 700 /var/log/init
 mount -o size=4m,nr_inodes=1k,mode=700 -t tmpfs tmpfs /var/log/init
fi

[     -d      /etc/init.d/conf.d ] ||
mkdir -pm 700 /etc/init.d/conf.d

series

if [ -f /proc/$!/cmdline ]; then kill $!; fi
