#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 500
# Required-Start: root-rw-retry
# Default-Start: S
# Short-Description: alternate roots if SA made mistake.
# Description: If /media/root is not expected to be encrypted
# 	and can not be mounted then present a selection of
#	alternate UUID and devices to be mounted as root.
### END INIT INFO

# Copyright 2012 through 2012 by Kyle Sallee,
# All rights reserved.
# For use with the Sorcerer distribution only.

if grep -v rootfs  /proc/mounts | grep -q " /media/root .*rw"; then exit 0; fi
if grep /media/root /etc/fstab | grep -q luks; then exit 0; fi
if [ -d /home ]; then exit 0; fi
if grep -q boot=IR /proc/cmdline; then exit 0; fi

. /lib/lsb/init-functions

only start

start(){
 media_root(){
  sed 's:#.*::' /etc/fstab |
  grep /media/root |
  tr '\t' ' ' |
  tr -s ' ' |
  cut -d ' ' -f1
 }

 root_menu(){
  dialog --backtitle alt_boot --stdout --no-cancel --title "Root Device Menu" \
         --menu "Please select device for /" 0 0 0 $( block )
 }

 block(){ find /dev -type b -printf '%p	%Y\n' | sed '/loop/d'; }
 new_root(){ echo "$( root_menu ) /media/root auto defaults 0 0" >> /etc/fstab; }

 not_mounted(){
  local OLD_DEV="$( media_root )"
  local MSG=$"$OLD_DEV
did not mount on /media/root
This outcome is undesirable,
but not unanticipated."

  dialog --backtitle root-alt --stdout --no-cancel --timeout 60 \
         --title "Please pardon the interruption." --msgbox \
         "$MSG" 0 0
 }

 choose(){
  dialog --backtitle alt_boot --item-help --stdout --no-cancel --timeout 60 \
         --title     "Root device decision menu" \
         --menu      "Please select an option within 60 seconds" 0 0 0 \
         "select"    "for manual selection of a device" \
                     "block devices from /dev will be displayed on a menu" \
         "initramfs" "for mouting the initramfs as root" \
                     "good for examining and trouble shooting a boot problem"
 }

 not_mounted
 if [ "$( choose )" == select ]; then
  sed -i '\,/media/root,d' /etc/fstab
  new_root
  /etc/init.d/root-rw start
 fi
}
