#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 500
# Should-Start: udev
# Default-Start: S
# Short-Description: loads the module
### END INIT INFO

. /lib/lsb/init-functions
only start stop restart status
