#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 500
# Default-Start: S
# Required-Start: proc
# Short-Description: sys mounts sysfs on /sys
### END INIT INFO

. /lib/lsb/init-functions

only start stop restart status
deny control
name /sys
options '-n -t sysfs sysfs'
