#!/bin/bash

### BEGIN INIT INFO
# Provides: gizmod
# Required-Start: $syslog run
# Should-Start:
# Required-Stop: kill
# Should-Stop: $syslog
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 6
# Short-Description: gizmod provides the gizmod server
# Description: gizmod provides the gizmod client
### END INIT INFO

. /lib/lsb/init-functions

PIDF=/var/run/gizmod.pid
SERV=/usr/bin/gizmod
NAME=gizmod

start()  {
  log_warning_msg  "$NAME starting"
  $SERV &
  sleep 0.1
  echo  $!  >  $PIDF
  log_success_msg  "$NAME started"
}

parse "$@"
