#!/bin/bash

### BEGIN INIT INFO
# Provides: sensors
# Required-Start: 
# Should-Start: modprobe udev
# Required-Stop: syslog kill 
# Should-Stop: 
# Default-Start: 2 3 4 5
# Default-Stop: 
# Short-Description: sensors sets hardware limits specified in /etc/sensors.conf
### END INIT INFO

. /lib/lsb/init-functions

NAME=sensors
CONF=/etc/sensors.conf
OPTS='-s'

help()  { echo "Usage: $0 {start}" 1>&2; }

parse "$@"
