#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 710
# Required-Start: sensors run
# Required-Stop: syslog kill 
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: sensord is lm_sensors hardware health monitoring daemon
### END INIT INFO

. /lib/lsb/init-functions

PIDF=/var/run/sensord.pid
SERV=/usr/bin/sensord
CONF=/usr/bin/sensord

# Configuration of sensord

SCAN=1m		# interval between scanning for sensor alarms
LAG=24h		# interval between logging  all sensor readings

# new values for SCAN and LAG can be specified in 
#    /etc/sensord.conf

[ -f /etc/sensord.conf ] &&
   . /etc/sensord.conf

OPTS="-i $SCAN -l $LAG"

parse "$@"
