#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 500
# Provides: wpa_priv
# Required-Start: proc var_run_wpa_priv
# Should-Start: udev
# Required-Stop: kill
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Starts wpa_supplicant for all wireless interfaces
### END INIT INFO

. /lib/lsb/init-functions

pnw(){
 [ -f          /proc/net/wireless ] &&
 tr ' ' '\n' < /proc/net/wireless |
 sed 's/://p;d' |
}

param(){
 local N
 local E=/etc/wpa_supplicant

 pnw |
 while read; do
  if   [ -f $E/wpa$REPLY.conf ]
  then CONF=$E/wpa$REPLY.conf
  elif [ -f $E/wpa_supplicant.conf ]
  then CONF=$E/wpa_supplicant.conf
  else CONF=
  fi
  if   [ -n "$CONF" ]
  then echo "$N-Dwext -i$REPLY -C$CONF"
  else echo "$N-Dwext -i$REPLY"
  fi
  N="-N "
 done
}

only start stop restart status
name wpa_priv
server /sbin/wpa_supplicant
options "-B $( param )"

 # Monitor connection status and run network (IP) configuration
 # script when wireless connection is established
 # Wait until wpa_supplicant is running:

# ((       WAIT = SECONDS + 10 ))
# while (( WAIT > SECONDS      )); do
#  [ -S /var/run/wpa_supplicant/$IF ] && break
#  echo -n .
#  sleep 0.25
# done

