#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 500
# Provides: wpa_priv
# Required-Start: proc var_run_wpa_priv
# Should-Start: udev
# Required-Stop: kill
# Default-Start: S
# Default-Stop: 0 1 6
# Short-Description: Starts wpa_supplicant for all wireless interfaces
### END INIT INFO

. /lib/lsb/init-functions

pnw(){
 [ -f          /proc/net/wireless ] &&
 tr ' ' '\n' < /proc/net/wireless |
 sed 's/://p;d'
}

param(){
 local N
 local E=/etc/wpa_supplicant

 pnw |
 while read; do
  if   [ -f     $E/wpa$REPLY.conf ]
  then CONF=" -c $E/wpa$REPLY.conf"
  elif [ -f     $E/wpa_supplicant.conf ]
  then CONF=" -c $E/wpa_supplicant.conf"
  fi
  echo "$N-Dwext -i$REPLY$CONF"
  N="-N "
 done
}

only start stop restart status
name wpa_supplicant
server /sbin/wpa_supplicant
options "-B -g /var/run/wpa_supplicant $( param )"
