#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 500
# Required-Start: proc wpa_supplicant
# Should-Start: udev
# Required-Stop: kill
# Default-Start: S
# Default-Stop: 0 6
# Short-Description: runs wpa_cli after wpa_supplicant during boot
### END INIT INFO

. /lib/lsb/init-functions

only start stop restart status
name wpa_cli
config /etc/wpa_supplicant/wpa_action.conf
server /sbin/wpa_cli
options "-a /etc/wpa_supplicant/wpa_action.conf"
