#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 500
# Provides: wpa_priv
# Required-Start: proc var_run_wpa_priv
# Should-Start: udev
# Required-Stop: kill
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Starts wpa_supplicant for all wireless interfaces
### END INIT INFO

. /lib/lsb/init-functions

pnw(){
 [ -f          /proc/net/wireless ] &&
 tr ' ' '\n' < /proc/net/wireless |
 sed 's/://p;d' |
 sed 's/^/-N -Dwext -i/'
}

WSC=/etc/wpa_supplicant/wpa_supplicant.conf

only start stop restart status
name wpa_priv
server /sbin/wpa_priv
if   [ -f "$WSC" ]
then options "-B -C$WSC /var/run/wpa_priv.pid $( pnw )"
else options "-B $( pnw )"
fi
