#!/bin/bash
# Copyright 2011, 2012 by Kyle Sallee,
# All rights reserved.
# For use with the Sorcerer distribution only.

# sentinel-retry periodically checks and retrys failed compilation attempts.

failed(){ find $EVENT -type f -perm -0040 -name \*Fail\* -printf "%f\n"; }
times(){ failed | LC_ALL=C grep "^$1" | wc -l; }
limit(){ (( $( times $1 ) > $TRIES )) && ! [ -f "$ACTI/$1" ]; }
retry(){ mv "$FAIL/$1" "$CAST/$1"; }
fail(){ [ -d $FAIL ] && find $FAIL -type f -mmin +$DELAY -printf "%f\n"; }
scan(){ fail | while read; do limit "$REPLY" || retry "$REPLY"; done; }
main(){ while sleep 900; do scan; done; }

if   [[     -x /usr/libexec/bash/sleep ]]
then enable -f /usr/libexec/bash/sleep sleep
fi

DELAY=${1:-30}
TRIES=${2:-1}

FAIL=/root/.sorcery/queue/cast/failed
CAST=/root/.sorcery/queue/cast
ACTI=/root/.sorcery/queue/cast/active
EVENT=/var/log/sorcery/event

main &>/dev/null &
exit 0
