#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 500
# Required-Start: $network empty run $local_fs
# Should-Start: tomoyo-domain
# Required-Stop:  $network
# Default-Start: S
# Default-Stop: 0 1 6
# Short-Description: a method for logging into the rootfs via ssh
### END INIT INFO

[ -f /media/root/real/sbin/sshd ] || exit 0

. /lib/lsb/init-functions

only start stop restart try-restart status
server /sbin/sshd
config /etc/ssh/sshd_config-rootfs
options "-f /etc/ssh/sshd_config-rootfs"
domain user

try-restart(){ :; }
    restart(){ :; }
