#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 510
# Required-Start: $local_fs
# Should-Start: udev
# Default-Start: S
# Short-Description: Sets resolution on 800 and 900 series Intel graphics chipsets
# Description: Sets resolution on 800 and 900 series Intel graphics chipsets.
#              It should be needed only for the 'i810' video driver but not
#              for the newer 'intel' driver
### END INIT INFO

. /lib/lsb/init-functions

SERV=/usr/sbin/915resolution
CONF=/etc/default/915resolution
NAME=915resolution

start(){
 . $CONF
 if   log_warning_msg "$NAME starting"; $SERV $MODE $XRES $YRES $BIT
 then log_success_msg "$NAME set"
 else log_failure_msg "$NAME failed"
 fi	 
}

status(){ $SERV -l; }

stop(){ log_success_msg "$NAME stopped"; }

parse "$@"
