#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 500
# Required-Start: var_lib_dbus
# Default-Start: S 1 2 3 4 5
# Short-Description: creates /var/lib/dbus/machine-id
### END INIT INFO

. /lib/lsb/init-functions

only start stop
name /bin/dbus-uuidgen
options --ensure
MAID=/var/lib/dbus/machine-id

start(){
 if   log_warning_msg "$OPTS"; $NAME $OPTS
 then log_success_msg "$OPTS"
 else log_failure_msg "$OPTS"; return 1
 fi
}

stop(){
 if   log_warning_msg "rm -f $MAID"; rm -f "$MAID"
 then log_warning_msg "rm -f $MAID"
 else log_warning_msg "rm -f $MAID"; return 1
 fi
}
