#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 510
# Provides: $mail
# Required-Start: $network $remote_fs run
# Required-Stop: kill
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 6
# Short-Description: exim is a mail transport agent
### END INIT INFO

. /lib/lsb/init-functions

pid_file /var/run/exim-daemon.pid
server /usr/sbin/exim
options '-bd -q15m'
