#!/bin/bash

# Copyright 2008, 2009, 2010, 2011 by Kyle Sallee,
# All rights reserved.
# For use with the Sorcerer distribution only.

. /etc/sorcery/config

expire_logs(){
 local EE=${EVENT_EXPIRE:-$EXPIRE}
 local LE=${LEECH_EXPIRE:-$EXPIRE}

 ( find "${EVENT_LOGS:-/var/log/sorcery/event}/"     -type f -mtime +$EE
   find "${LEECH_LOGS:-/var/log/sorcery/leech}/"     -type f -mtime +$LE
 ) 2>/dev/null | escape_qs | xargs -r --max-lines=64 rm -f
}

prune_common_cache(){
 declare -i R=0  S=0 LIM=0    SIZE=0
 declare -i SAV_CX=0 OLD_CX=0
 local      SAV      OLD      FILE

 ext() { sed -r 's:(.*\.)(tar)$:\1\2\n\1tgz\n\1\2.gz\n\1\2.bz2\n\1\2.xz\n\1\2.7z\n\1\2.lzma\n\1\2.lz:'; }
 size(){ files   | while read F; do echo -n "$F$TAB"; finfo -s "$F"; done; }
 age() { files   | while read F; do echo -n "$F$TAB"; finfo -m "$F"; done; }
 sum() { cut -f2 | while read R; do (( S+=R )); echo "$S"; done | tail -n1; }

 SAV="$( ( echo "$1" | ext
           echo "$2"
         )           |
   LC_ALL=C sort     | uniq -d | size
 )"

 OLD="$( ( echo  "$1" | ext | sed p
           echo  "$2"
         )            |
   LC_ALL=C sort      | uniq -u | age |
   LC_ALL=C sort -g -t "$TAB" -k2 | cut -f1 | size
 )"

 SAV_CX="$( echo "$SAV" | sum )"
 OLD_CX="$( echo "$OLD" | sum )"

 (( LIM = SAV_CX * $3 / 100 ))

 if     (( OLD_CX > LIM  )); then echo "$OLD" |
  while (( OLD_CX > LIM  ))  &&   read  FILE SIZE
  do    (( OLD_CX-= SIZE )); echo     "$FILE"
  done
 fi | escape_qs | xargs -r --max-lines=64 rm -f
}

prune_ccache_cache(){
 mkdir_p $CCACHE_CACHE
 prune_common_cache \
  "$( show_installed | sed "s:^:$CCACHE_CACHE/:; s:$:.tar:" )" \
  "$( find $CCACHE_CACHE/ -type f )" \
  "$CCACHE_KEEP"
}

prune_archive_cache(){
 local           SCX="$( cat $ORDER_INDEX | wc -l )"
 if    (( 2560 > SCX )); then return; fi

 mkdir_p $ARCHIVE_CACHE
 prune_common_cache \
  "$( snapshot | pipe view_index av | LC_ALL=C sort -u | 
      sed -r "s:([^\t]*)\t(.*):$ARCHIVE_CACHE/$HOSTTYPE/\1/\2/\1-\2.tar:"
    )" \
  "$( find $ARCHIVE_CACHE/$HOSTTYPE/ -type f )" "$ARCHIVE_KEEP"
 find      $ARCHIVE_CACHE/ -type d -empty | xargs -r --max-lines=256 rmdir
 find      $ARCHIVE_CACHE/ -type d -empty | xargs -r --max-lines=256 rmdir
}

prune_source_cache(){
 local           SCX="$( view_index src | wc -l )"
 if    (( 3000 > SCX )); then return; fi

 mkdir_p $SOURCE_CACHE
 prune_common_cache \
  "$( view_index src |
      sed "s:.*$TAB:$SOURCE_CACHE/:" | tarname )" \
  "$( find          $SOURCE_CACHE/ -type f | filter "$LOCAL_EXCLUDE" )" "$SOURCE_KEEP"
 find               $SOURCE_CACHE/ -type d -empty | xargs -r --max-lines=256 rmdir
 find               $SOURCE_CACHE/ -type d -empty | xargs -r --max-lines=256 rmdir
}

prune_failed_cache(){
 find "${FAILED_CACHE:-/var/tmp/failed}/" \
  -maxdepth 1 -mindepth 1 -type d  -mtime +7 | xargs --max-lines=16 rm -fr
}

prune_archive_cache
prune_ccache_cache
prune_source_cache
prune_failed_cache
expire_logs
