#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 500
# Should-Start: snd-mixer-oss snd-pcm-oss snd-seq-oss
# Default-Start: 1 2 3 4 5
# Short-Description: alsactl restores the audio mixer volume settings
### END INIT INFO

. /lib/lsb/init-functions

only start
server /usr/sbin/alsactl
options restore
config /var/lib/alsa/asound.state
