#!/bin/bash

### BEGIN INIT INFO
# Provides: snd-mixer-oss
# Required-Start: 
# Should-Start: snd-pcm-oss
# Required-Stop:
# Default-Start: 1 2 3 4 5
# Default-Stop:
# Short-Description: snd-mixer-oss loads the module
# Description: snd-mixer-oss loads the module
### END INIT INFO

. /lib/lsb/init-functions

NAME=snd-mixer-oss

parse "$@"
