#!/bin/sh


start()  {
  echo  -n  "Starting Regina Stack..."
  /usr/bin/rxstack  -d  >/dev/null   
  echo  "done."
}

stop()  {
  echo  -n  "Stopping Regina Stack..."
  /usr/bin/rxstack  -k  >/dev/null
  echo  "done."
}

help()  {
  echo  "Usage:  $0  {start|stop|restart}"
}  
  
case $1 in
    start)                       start  ;;
  restart)  stop  &&  sleep  1;  start  ;;
     stop)  stop                        ;;
        *)  help                        ;;
esac
