#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 710
# Provides: imap4
# Required-Start: $local_fs $network authdaemon
# Required-Stop: $local_fs
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 6
# Short-Description: courier-imap, IMAP4 daemon
### END INIT INFO

. /lib/lsb/init-functions

SERV=/usr/libexec/imapd.rc
NAME=courier-imap4

start(){
 log_warning_msg "$NAME starting"; $SERV start
 log_success_msg "$NAME started"
}

stop(){
 log_warning_msg "$NAME stopping"; $SERV stop
 log_success_msg "$NAME stopped"
}

cd /usr/libexec/
parse "$@"
