#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 510
# Provides: $mail
# Required-Start: $network
# Should-Start: $remote_fs
# Required-Stop: $network
# Should-Stop: $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: postfix is a MTA
### END INIT INFO

. /lib/lsb/init-functions

server /usr/sbin/postfix
name postfix
options start

#PROCNAME=/usr/libexec/postfix/master
#status(){
# PIDS="$( pidofproc $PROCNAME )"
# if   [ -n "$PIDS" ]; then log_warning_msg "$NAME is running"; return 0
# elif [ -f "$PIDF" ]; then log_warning_msg "$NAME is dead and $PIDF exists"; return 1
#                      else log_warning_msg "$NAME is not running"; return 3
# fi
#}

status(){ $SERV status; }
reload(){ $SERV reload; }

stop(){
 log_warning_msg "$NAME stopping"; $SERV stop
 log_success_msg "$NAME stopped"
}
