#!/bin/dash

### BEGIN INIT INFO
# Required-Start: proc
# Default-Start: S
# Short-Description: cpufreq_gouvernor sets the box's cpu freq gouvernor
### END INIT INFO

. /lib/lsb/init-functions

start(){
 log_warning_msg "cpufreq_gouvernor setting"
 cpus=$(ls /sys/devices/system/cpu/ | grep "cpu.$")
 if [ -f           /etc/cpufreq_gouvernor ]; then
   read   REPLY < /etc/cpufreq_gouvernor
   for cpu in ${cpus}; do
        {
        log_warning_msg "setting $REPLY on $cpu" &&
   	cpufreq-set -g ${REPLY} -c ${cpu##cpu}  &&
	log_success_msg "cpufreq_gouvernor is now $REPLY"
        } ||
        log_failure_msg "couldn't set $REPLY on $cpu"
   done
 else
        log_failure_msg "/etc/cpufreq_gouvernor don't  exist"
 fi
}

parse "$@"
