#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 400
# Required-Start: proc sys
# Should-Start: udev
# Default-Start: S
# Short-Description: loads CPU frequency governor module
### END INIT INFO

. /lib/lsb/init-functions
only start stop restart status
