#!/bin/sh

   VERSION=( "0.3.6" )
   CATEGORY="file-share"
 ATTRIBUTE="new console"
    SOURCE=("rtorrent-${VERSION}.tar.gz")
       URL=("http://libtorrent.rakshasa.no/downloads")
REPOSITORY=("true"
            "svn co svn://rakshasa.no/libtorrent/trunk/rtorrent"
            "svn up svn://rakshasa.no/libtorrent/trunk/rtorrent")
 FRESHMEAT="rtorrent"
  HOMEPAGE="http://libtorrent.rakshasa.no"
#this is an unofficial variable, put here only what is required to build
#not what is required to run"
 BUILD_REQ=""
       REQ=("$BUILD_REQ libtorrent")
  ESTIMATE=""
      DESC="rTorrent - The ncurses client to bittorrent
The client uses ncurses and is ideal for use with screen or dtach. It supports saving of sessions and allows the user to add and remove torrents."


