#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 710
# Required-Start: dmsetup dm-crypt
# Should-Start: mdadm udev vgchange
# Required-Stop: $syslog
# Default-Start: S
# Default-Stop: 0 6
# Short-Description: cryptmount-early configures encrypted devices at boot.
# Description: cryptmount-early configures encrypted devices at boot.
# If /boot exists on a regular partition and
# / exists on an encrypted partition
# then cryptmount-early configures the device so that
# it is available by the time the mount script mounts devices
# that are listed in /etc/fstab
### END INIT INFO

. /lib/lsb/init-functions

NAME=cryptmount-early
SERV=/bin/cryptmount
CONF=/etc/default/cryptmount

status(){
 local ON OFF
 for TARGET in $CM_EARLYDV
 do [ -b "/dev/mapper/$TARGET" ] && ON+="$TARGET " || OFF+="$TARGET "
 done
 if [ "$OFF" ]
 then log_warning_msg "$OFF not active"; return 3;
 else log_warning_msg "$ON active";
 fi
}

stop(){
 if   log_warning_msg "$NAME stopping"; $SERV -n --release $CM_EARLYDV
 then log_success_msg "$NAME stopped"
 else log_failure_msg "$NAME not stopped"; status
 fi
}

CM_EARLYDV=
if   [ -f $CONF ] && . $CONF && [ -n "$CM_EARLYDV" ]
then OPTS="--prepare $CM_EARLYDV"; parse "$@"
fi
