#!/bin/bash

### BEGIN INIT INFO
# Provides: fuse $fuse
# Required-Start: $local_fs
# Should-Start: udev
# Required-Stop: halt reboot
# Default-Start: S
# Default-Stop: 0 6
# Short-Description: fuse starts fuse at boot
# Description: fuse starts fuse at boot
#   Okay not the best init file.
#   I will improve it later.
### END INIT INFO

. /lib/lsb/init-functions


start()  {
  log_warning_msg  "fuse starting"
  modprobe fuse  &>/dev/null
  if    mount -t fusectl none /sys/fs/fuse/connections  2>/dev/null
  then  log_success_msg  "fuse started"
  else  log_failure_msg  "Unable to mount fuse control filesystem"
  fi
}

stop() {
  log_warning_msg  "fuse stopping"
  if    umount     /sys/fs/fuse/connections  2>/dev/null
  then  log_success_msg  "fuse stopped";      sleep 0.5
  else  log_failure_msg  "fuse not stopped";  sleep 0.5
  fi
}

help()  {  echo "Usage: $0 {start|stop}" 1>&2;  return 3;  }

case  $1  in
  start)  start  ;;
   stop)  stop   ;;
try-restart) :   ;;
      *)  help   ;;
esac
