#!/bin/bash
# Copyright 2011 through 2012 by Kyle Sallee,
# All rights reserved.
# For use with the Sorcerer distribution only.

if    [ -d          /etc/networks.d ]; then
 if   [ -n "$( find /etc/networks.d -maxdepth 1 -type f )" ]
 then exit 0
 fi
fi

interfaces(){
 ip link show |
 LC_ALL=C grep -v "lo:\|^ " |
 tr -d ' ' |
 cut -d : -f2
}

wireless(){ iwconfig 2>/dev/null | sed "/^ /d; s/ .*//"; }

for REPLY in $( wireless   ); do iwconfig  $REPLY mode Managed essid any; done
for REPLY in $( interfaces ); do dhcpcd -q $REPLY; done
