#!/bin/bash

### BEGIN INIT INFO
# Provides: winbindd
# Required-Start: nmbd run
# Should-Start:
# Required-Stop: nmbd
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: winbindd provides a name service switch daemon for resolving names from NT servers
# Description: winbindd provides a name service switch daemon for resolving names from NT servers
### END INIT INFO

. /lib/lsb/init-functions

PIDF=/var/run/winbindd.pid
SERV=/usr/sbin/winbindd
NAME=winbindd

reload()  {
  PIDS="$( pidofproc -p $PIDF $SERV )"
  if    [ -n            "$PIDS" ]
  then  kill  -s SIGHUP  $PIDS  &&
        log_success_msg "$NAME configuration reloaded"
  fi
}

help()  {
  echo "Usage: $0 {restart|try-restart|reload|force-reload|start|status|stop}" 1>&2
}

case  $1  in
       restart)      restart  ;;
   try-restart)  try_restart  ;;
        reload)  reload       ;;
  force-reload)  reload       ;;
         start)  start        ;;
        status)  status       ;;
          stop)  stop         ;;
             *)  help         ;;
esac
