#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 500
# Required-Start: hostname $local_fs run
# Should-Start: hwclock
# Required-Stop: kill
# Default-Start: 1 2 3 4 5
# Short-Description: msyslog-logs creates log files for msyslogd
### END INIT INFO

if [ "$1" == try-restart ]; then exit 2; fi

. /lib/lsb/init-functions

name msyslog-logs

start(){
 load(){
  [ -f $CONF ] &&
  sed 's:#.*::; s:[^/]*/:/:; \,^/dev/,d;\,/,p; d' $CONF |
  while read; do
   [ -d ${REPLY%/*} ] || mkdir -p    ${REPLY%/*}
   [ -f ${REPLY}    ] || echo  -n >> ${REPLY}
  done
 }

 if   log_warning_msg "$NAME starting"; load
 then log_success_msg "$NAME started"
 else log_failure_msg "$NAME not started"
 fi
}

help(){ echo "Usage: $0 {start}" 1>&2; }
