#!/bin/bash
### BEGIN INIT INFO
# Default-Mode: 500
# Required-Stop: kexec $local_fs root-ro udev
# Should-Stop: tmp
# Default-Stop:
# Short-Description: creates boot filesystems
### END INIT INFO

# Copyright 2007 through 2011 by Kyle Sallee, all rights reserved.
# for use with Sorcerer only

. /lib/lsb/init-functions

only stop reload force-reload status
name /boot/initrf/etc
INIT=initramfs-etc
SKIP="[32G"

allpaths(){ sed -nr "p;:a;s:(.+)/.*:\1:p;ta" | sort -u; }

exists(){ while read; do [[ -e $REPLY ]] && echo "$REPLY"; done; }

every(){
 find ${NAME/\/boot\/initrf/} |
 sed "\
\,^/etc/[^/]*\.old$,d
\,^/etc/X11,d
\,^/etc/sorcery/,d
\,^/etc/selinux/,d
\,^/etc/asciidoc/,d
\,^/etc/avahi/,d
\,^/etc/chipcard,d
\,^/etc/courier/,d
\,^/etc/cups/,d
\,^/etc/elvis.default/stubs/,d
\,^/etc/extlinux/,d
\,^/etc/fonts/,d
\,^/etc/gconf/,d
\,^/etc/gdm/,d
\,^/etc/gimp/,d
\,^/etc/gtk/,d
\,^/etc/httpd/,d
\,^/etc/kde,d
\,^/etc/logcheck,d
\,^/etc/mono/,d
\,^/etc/mplayer/,d
\,^/etc/mtab,d
\,^/etc/openldap/,d
\,^/etc/php.ini$,d
\,^/etc/prelink,d
\,^/etc/sane\.d/,d
\,^/etc/services\.d/,d
\,^/etc/sound/,d
\,^/etc/squid/,d
\,^/etc/xdg/,d
\,^/etc/boot-blaze,d
\,^/etc/xml,d"
}

initrf_update(){

 local          TEMPIF=/tmp/initramfs.$$.$RANDOM$RANDOM
 rm    -rf     $TEMPIF
 mkdir -pm 700 $TEMPIF/boot/initrf

 local  COMMON="$TEMPIF/$NAME"

 every | allpaths | exists | cpio -o -H newc --quiet | gzip -1 > $COMMON
 chmod 600 $COMMON

 [  -f /boot/initrf ] &&
 rm -f /boot/initrf

 cp -a  $TEMPIF/boot /
 rm -fr $TEMPIF
 sync
}

initrf_present(){ [ -f $NAME ] || return 1; }

initrf_current(){
 also(){
  var=$1; shift
  while [ -n "$1" ]
  do if [ -e "$1" ]; then eval $var+=" $1"; fi; shift
  done
 }

 local FIND='/etc/bash.d'
 also  FIND \
 /etc/cgroup /etc/exports /etc/fstab /etc/fstab.rootfs /etc/group \
 /etc/hostname /etc/init.d /etc/inittab /etc/lvm /etc/mdadm.conf \
 /etc/modprobe.d /etc/multipath.conf /etc/networks.d /etc/passwd \
 /etc/rc.d /etc/shadow /etc/udev /etc/tomoyo /etc/wpa_supplicant

 if   find $FIND -newer $NAME | grep -q .
 then return 1
 fi

 if [ -f /var/log/init/failed/$INIT/stop ]; then return 1; fi
} 

run(){
 if   log_warning_msg "$NAME $SKIP updating"; initrf_update
 then log_success_msg "$NAME $SKIP updated"
 else log_failure_msg "$NAME $SKIP failed"; false
 fi
}

status(){
 if   log_warning_msg "$NAME $SKIP checking"; initrf_present && initrf_current
 then log_success_msg "$NAME $SKIP checked; status:     current"
 else log_warning_msg "$NAME $SKIP checked; status: not current"; return 1
 fi
}

stop(){ status || run; }
force_reload(){ run; }
reload(){ DONE=true; stop; }

export LC_ALL=C
