#!/bin/bash

### BEGIN INIT INFO
# Provides: empty
# Required-Start: $local_fs
# Should-Start:
# Required-Stop: 
# Default-Start: 2 3 4 5
# Default-Stop:
# Short-Description: lock mounts tmpfs on /var/empty
# Description: lock mounts tmpfs on /var/empty
### END INIT INFO

. /lib/lsb/init-functions

NAME='/var/empty'
SERV='mount'
OPTS='-o defaults,size=1m,nr_inodes=1k,mode=0700 -t tmpfs tmpfs'

parse $1
