#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 500
# Required-Start: $network empty run $local_fs
# Required-Stop:  $network
# Default-Start: S
# Default-Stop: 0 1 6
# Short-Description: a method for logging into the keep via ssh
### END INIT INFO

[ -f /media/root/sbin/sshd ] || exit 0

. /lib/lsb/init-functions

deny try-restart
pid_file /var/run/sshd_keep.pid
server /sbin/sshd
config /etc/ssh/sshd_config_keep
options "-f /etc/ssh/sshd_config_keep"

try-restart(){ :; }
    restart(){ :; }
