#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 510
# Provides: $cron
# Required-Start: $local_fs run
# Required-Stop: kill
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: mcron is a vixie cron replacement
### END INIT INFO

. /lib/lsb/init-functions

SOCK=/var/cron/socket
PIDF=/var/run/cron.pid
SERV=/usr/sbin/cron
CONF=/var/cron/tabs
NAME=mcron
OPTS='-n'

export TERM=dumb

start(){
 clear_socket(){ if ! status &>/dev/null; then rm -f $SOCK; fi; }

 if ! [ -d $CONF ]; then
      log_warning_msg "$NAME not started; $CONF does not exist"; return; fi
 if   log_warning_msg "$NAME starting"; clear_socket; start_daemon -p $PIDF $SERV $OPTS &>/dev/null
 then log_success_msg "$NAME started"
 else log_failure_msg "$NAME not started"; status
 fi
}

parse "$@"
