#!/bin/bash
### BEGIN INIT INFO
# Default-Mode: 500
# Default-Start: 1 2 3 4 5
# Short-Description: creates file /var/log/console
### END INIT INFO

if [ "$1" == try-restart ] || ! [ -s /sbin/bootlogd ]; then exit; fi

. /lib/lsb/init-functions

run(){
 log_warning_msg "/var/log/console creating"
 touch           "/var/log/console"
 log_success_msg "/var/log/console created"
}

[ -f /var/log/console ] || run
