#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 500
# Required-Start: fstab root-ro
# Should-Start: cryptsetup dmsetup hwclock loadkeys mapper mdadm udev vgchange 
# Default-Start: S
# Short-Description: fsck checks local filesystems during boot
### END INIT INFO

. /lib/lsb/init-functions

start(){
 fsc(){
  local FORCE
  if grep -q fastboot  /proc/cmdline; then return; fi
  if grep -q forcefsck /proc/cmdline; then FORCE=-f; fi

  fsck -C -A -p $FORCE 1>/dev/console 2>&1 0</dev/console
  if [ $? -gt 1 ]; then
   log_failure_msg 'fsck failed' 1>/dev/console 2>&1
   log_failure_msg 'Repair file systems by running /sbin/fsck' 1>/dev/console 2>&1
   sulogin -t 120 1>/dev/console 2>&1 0</dev/console
  fi
 }

 log_warning_msg 'Local file systems checking'; fsc
 log_success_msg 'Local file systems checked'
}
       stop(){ :; }
    restart(){ :; }
try_restart(){ :; }
parse "$@"
