#!/bin/bash

### BEGIN INIT INFO
# Provides: ICE-unix
# Required-Start: $local_fs
# Should-Start: tmp
# Required-Stop: 
# Default-Start: 1 2 3 4 5
# Default-Stop:
# Short-Description: ICE-unix creates /tmp/.ICE-unix
### END INIT INFO

. /lib/lsb/init-functions

NAME='/tmp/.ICE-unix'

start(){
 if   [ -d $NAME ]; then return; fi
 if   log_warning_msg "$NAME creating"; mkdir -pm 1777 $NAME
 then log_success_msg "$NAME created"
 else log_failure_msg "$NAME not created"; return 1
 fi
}
       stop(){ :; }
    restart(){ :; }
try_restart(){ :; }
parse "$@"
