#!/bin/bash
### BEGIN INIT INFO
# Required-Stop: $local_fs proc udev
# Should-Stop: tmp
# Default-Stop: 0 6
# Short-Description: lilo regenerates /etc/lilo/conf when necessary
### END INIT INFO

# Copyright 2008-2011 by Kyle Sallee, all rights reserved.
# for use with Sorcerer only

. /lib/lsb/init-functions

LILO=/etc/lilo.conf
NAME=/etc/lilo/conf
CONF=/etc/lilo/conf
FAST=/etc/lilo/fast
HEAD=/etc/lilo/head
TAIL=/etc/lilo/tail
DONE=false

lilo_conf_update(){
 reorder(){
  if [ -z "$LVER" ]; then cat -;
  else
   local CX=0
   while read; do
    case $CX in
     0) if   [ "$REPLY" == "$LVER" ]; then        LVER=; echo "$REPLY"; fi ;;
     1) if   [ -n          "$LVER" ]; then echo "$LVER"; echo "$REPLY"; fi ;;
     *) if ! [ "$REPLY" == "$LVER" ]; then               echo "$REPLY"; fi ;;
    esac
    (( CX++ ))
   done
  fi
 }

 img(){
  echo "image			=	/boot/$REPLY/linux"; $INRF &&
  echo "	initrd		=	/boot/$REPLY/initrf"
  echo "	label		=	$REPLY"
  echo "	read-only"
  echo "	$1"
  echo
 }

 local INRF ICX=0
 local LVER="$( uname -r )"
 [ -f /boot/$LVER/linux ] || LVER=

 if   [ -f /etc/init.d/initramfs ] &&
      [ -x /etc/init.d/initramfs ]
 then INRF=true
 else INRF=false
 fi

 if ! [ -f $HEAD ]; then exit 1; fi

 cp $HEAD $CONF
 cp $HEAD $FAST

 REPLY=fast img restricted >> $FAST

 find /boot -mindepth 2 -maxdepth 2 -type f -name linux -printf '%T@\t%h\n' |
 sort -gr |
 sed '\,/boot/fast,d; \,/boot/rescue,d; s:.*/::' |
 reorder |
 while read REPLY; do
  if   (( 4 > ICX ))
  then img restricted
  else rm -fr /boot/$REPLY /lib{,.sav}/modules/$REPLY{,.old}
  fi
  (( ICX++ ))
 done | tee -a $FAST >> $CONF

 if   [ -f /boot/rescue/initrf ]
 then REPLY=rescue img mandatory | tee -a $FAST >> $CONF
 fi

 if   [ -f $TAIL ]
 then cat  $TAIL | tee -a $FAST >> $CONF
 fi

 if ! [ -h  $LILO ] ||
    ! [ -f  $LILO ]
 then rm -f $LILO; ln -s lilo/conf $LILO
 fi

 if   $INRF && ! $DONE
 then /etc/init.d/initramfs reload
 fi

 if   ! [ -f /etc/init.d/find_ir ]
 then /sbin/lilo -P ignore -C $CONF
 fi
}

both(){
 find /boot -mindepth 2 -maxdepth 2 -type f -name linux -printf '%P\n'
 sed 's:#.*::;s: ::g;s:\t::g;s:image=/boot/::p;d' $CONF
}

current(){ 
 [       -h  $LILO ] &&
 [       -f  $LILO ] &&
 [       -f  $CONF ] &&
 [ $CONF -nt $HEAD ] &&
 [ $CONF -nt $TAIL ] &&
 ! both | sed '\,fast/linux,d' | sort | uniq -u | grep -q .
}

stop(){
 if   log_warning_msg "$NAME updating"; lilo_conf_update
 then log_success_msg "$NAME updated"
 else log_failure_msg "$NAME failed"
  if   [ -n $1 ]
  then sulogin -t 300 1>/dev/console 2>&1 0</dev/console
  fi
 fi
}

status(){
 if   log_warning_msg "$NAME checking"; current
 then log_success_msg "$NAME checked; status:     current"
 else log_warning_msg "$NAME checked; status: not current"; return 1
 fi
}

export LC_ALL=C

if ! [ -d /boot ] ||
     [ -z "$( find /boot -mindepth 2 -maxdepth 2 -type f -name linux )" ]
then return
fi

case $1 in
 reload) DONE=true
         status || stop   ;;
 status) status ;;
  force)           stop   ;;
   stop) status || stop s ;;
      *) status || stop   ;;
esac
