#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 700
# Default-Start: S
# Short-Description: creates directory /media/root if it is missing
### END INIT INFO

. /lib/lsb/init-functions

start(){
 if [ -d /media/root ]; then return; fi
 if   log_warning_msg '/media/root directory creating'; mkdir -p /media/root
 then log_success_msg '/media/root directory created'
 else log_failure_msg '/media/root directory not created'
 fi
}

try_restart(){ :; }

parse "$@"
