#!/bin/dash

### BEGIN INIT INFO
# Required-Start: proc sys modprobe-r udev
# Default-Start: S
# Short-Description: modprobe loads modules during boot
### END INIT INFO

if [ "$1" = try-restart ]
then exit
fi

. /lib/lsb/init-functions

if    [ -x /sbin/modprobe ]; then
 if   [ -f /etc/modules   ]; then sed 's:#.*::;/^ *$/d' /etc/modules; fi
 if   [ -d /etc/dev.old   ] &&
    ! [ -d /opt           ]; then
  find /lib/modules -mindepth 3 -type f |
  sed 's:.*/::;s:\.ko$::'
 fi
fi |
while read REPLY; do
 if log_warning_msg "Module $REPLY loading" && modprobe $REPLY
 then log_success_msg "Module $REPLY loaded"
 else log_failure_msg "Module $REPLY not loaded"
 fi
done
