#!/bin/bash

### BEGIN INIT INFO
# Required-Start: proc sys modprobe-r dev-cp
# Default-Start: S
# Short-Description: modprobe loads modules during boot
### END INIT INFO

if [[ $1 == try-restart ]] || ! [[ -x /sbin/modprobe ]] || ! [[ -f /etc/modules ]]
then exit
fi

. /lib/lsb/init-functions

mp(){
 sed 's:#.*::;/^ *$/d' /etc/modules |
 while read; do modprobe $REPLY; done
}

log_warning_msg 'Modules loading'; mp
log_success_msg 'Modules loaded'
