#!/bin/bash
# Copyright 2011 by Kyle Sallee
# All Rights Reserved
# For use on Sorcerer only

trap : INT QUIT TSTP
export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
umask 022

run(){
 if ! [ -f $1 ]; then return 1; fi
 if ! [ -x $1 ]; then return 1; fi

 local n="${1##*/}"; n=${n:3:256}
 local f=/var/log/init/failed/$n
 local p=/var/log/init/passed/$n
 local s=/var/log/init/$n

 echo "$1 $2"
 echo "$1 $2" > $s

 if   grep -q "dialog\|fsck\|sulogin\|omit log" $1
 then $1 $2
 else $1 $2 &>> $s
 fi

 if   [ $? == 0 ]
 then sed 1d $s; mv $s $p
 else sed 1d $s; mv $s $f
 fi
}

series(){
 for S in /etc/rc.d/rcS.d/*; do run $S start; done
 echo End sysinit
}

md(){ [ -d $1 ] || mkdir -p $1; }

I=/etc/init.d
L=/var/log/init
D=$I/dev.d

[ -f $L/sysinit ] && exit

/sbin/agetty -f /etc/issue.rootfs /dev/tty7 9600 &

if   [ -c $D/si ] &&  echo > $D/si
then cap(){ tee $L/sysinit > $D/si; }
else cap(){ tee $L/sysinit; }
fi

md $L
md $D
if   ! [    -f               /proc/mounts ] ||
     ! grep -q /var/log/init /proc/mounts; then
 mount -o size=4m,nr_inodes=1k,mode=700 -t tmpfs tmpfs $L
 mkdir -p /var/log/init/{fail,pass}ed
fi
series 2>&1
#series 2>&1 | cap

if [ -f /proc/$!/cmdline ]; then kill $!; fi
