#!/bin/bash
trap : INT QUIT TSTP
export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
umask 022

run(){
 for S in /etc/rc.d/rcS.d/*
 do $S start
 done
 echo End sysinit
}

md(){ [ -d $1 ] || mkdir -p $1; }
mn(){ [ -c $1 ] || mknod $1 c 5 1; }

I=/etc/init.d
L=$I/log.d
D=$I/dev.d

[ -f $L/sysinit ] && exit

md $L
md $D
mn $D/si
mn $D/rl
mount -o size=1m,nr_inodes=8 -t tmpfs tmpfs $L
run 2>&1 | tee $L/sysinit > $D/si
