#!/bin/bash
### BEGIN INIT INFO
# Default-Mode: 700
# Default-Start: 6
# Required-Start: finale
# Should-Start: reboot-kexec
# Short-Description: reboots the box
### END INIT INFO

. /lib/lsb/init-functions

case $1 in
start) log_success_msg Rebooting; reboot -d -f -i  ;;
esac
