#!/bin/dash

### BEGIN INIT INFO
# Required-Start: cryptsetup fstab proc sys
# Should-Start: cryptmount-early cryptsetup dmsetup fstab mapper mdadm $network udev vgchange
# Required-Stop: $local_fs
# Default-Start: S
# Short-Description: During non initramfs booting root-ro re-mounts / read-only
### END INIT INFO

if [ "$1" = try-restart ] || ! [ -d /opt ]; then exit; fi

. /lib/lsb/init-functions

start(){
 if   log_warning_msg 'root mounting read only'; mount -n -o remount,ro /
 then log_success_msg 'root mounted  read only'
 else log_failure_msg 'root not mounted'
 fi
}

stop(){ :; }
try_restart(){ :; }
parse "$@"
