#!/bin/bash                                                   

### BEGIN INIT INFO
# Required-Start: root-rw
# Required-Stop: $local_fs                                                      
# Default-Start: S                                                              
# Default-Stop:
# Short-Description: Second chance at mounting / read-write
### END INIT INFO

if [ "$1" = try-restart ] || [ -d /opt ] ||
   grep -q boot=IR /proc/cmdline ||
   grep -v rootfs  /proc/mounts  | grep -q " /media/root .*rw"
then exit
fi

echo > /tmp/coldplug
/etc/init.d/dev-cp start
/etc/init.d/modprobe-coldplug start
/etc/init.d/root-rw start
