#!/bin/bash

### BEGIN INIT INFO
# Provides: rtc-cmos
# Should-Start: udev
# Required-Start:
# Required-Stop:
# Default-Start:S
# Default-Stop:
# Short-Description: rtc-cmos loads the module
# Description: rtc-cmos loads the module
### END INIT INFO

. /lib/lsb/init-functions

NAME=rtc-cmos

parse "$@"
