#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 700
# Required-Start: $local_fs
# Required-Stop:  $local_fs
# Default-Start: 1 2 3 4 5
# Default-Stop: 0 6
# Short-Description: swap starts and stops swaps specified in /etc/fstab
### END INIT INFO

. /lib/lsb/init-functions

start(){
 if   log_warning_msg "swap starting"; swapon -a
 then log_success_msg "swap started"
 else log_failure_msg "swap not started"
 fi
}

stop(){
 if   log_warning_msg "swap stopping"; swapoff -a
 then log_success_msg "swap stopped"
 else log_failure_msg "swap not stopped"
 fi
}

parse "$@"
