#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 500
# Default-Stop: 6
# Required-Stop: mount
# Short-Description: kexec prepares box for reboot faster.
### END INIT INFO

. /lib/lsb/init-functions

only help

stop_broke(){
 V="$( find /boot -maxdepth 2 -mindepth 2 -name linux -printf '%T@\t%h\n' |
       grep -v /boot/rescue |
       sort -gr | head -n 1 | sed 's:.*/::' )"
 if   [ -f   /boot/$V/initrf ]; then I="--initrd=/boot/$V/initrf"
 elif [ -d   /boot/$V/initrf ]; then
  I="$( find /boot/$V/initrf/ -type f -printf "--initrd=%p\n" )"
 fi
 L="-l /boot/$V/linux"

 if   log_warning_msg "kexec $L $I run"; kexec $L $I
 then log_success_msg "kexec $L $I ran"
 else log_success_msg "kexec $L $I failed"
 fi
}
