#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 510
# Default-Start: S
# Short-Description: loopback starts loopback device
### END INIT INFO

. /lib/lsb/init-functions

start(){
 log_warning_msg "loopback configuring"
 /sbin/ip addr replace 127.0.0.1 dev lo
 /sbin/ip link set lo up
 log_success_msg "loopback configured"
}

case $1 in
 start) start ;;
esac
