#!/bin/bash
### BEGIN INIT INFO
# Default-Mode: 510
# Required-Start: avahi-daemon run
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Required-Stop: avahi-daemon
# Short-Description: avahi-dnsconfd is a ZeroConf daemon for mDNS and service registration
### END INIT INFO

. /lib/lsb/init-functions

server /usr/sbin/avahi-dnsconfd
pid_file /var/run/avahi-dnsconfd.pid
name avahi-dnsconfd
options -D

stop(){
 log_warning_msg "$NAME stopping"; $SERV -k
 log_success_msg "$NAME stopped"
}

reload(){
 $SERV -r
 log_success_msg "$NAME configuration reloaded"
}
