#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 510
# Provides: $syslog
# Required-Start: hostname $local_fs
# Should-Start: hwclock ntpd
# Required-Stop: kill
# Default-Start: 1 2 3 4 5
# Default-Stop: 0 6
# Short-Description: syslog-ng is a replacement for sysklog and syslog
### END INIT INFO

. /lib/lsb/init-functions

server /usr/sbin/syslog-ng
