#!/bin/bash

### BEGIN INIT INFO
# Required-Start: $local_fs run
# Required-Stop:  $local_fs kill
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: bxz xz compresses tarballs in the background
# Description: bxz provides background compression of tarballs.
# bxz enables more disk space to be conserved by
# recompressing tarballs more efficiently in the background
# while the box has a low loadavg
#
# To specify options to pass to xz by creating file:
# /etc/init.d/conf.d/bxz
#
# and uncomment the line:
#
# options "-9e"
#
# Since -9e causes xz to use nearly 700 megabytes of RAM,
# replace the -9e with desired command line parameters for xz.
### END INIT INFO

[ -d /boot/isolinux ] && exit

. /lib/lsb/init-functions

pid_file /var/run/bxz.pid
server   /usr/sbin/bxz

parse "$@"
