#!/bin/bash

trap    ":" INT QUIT TSTP

parallelize() {
  for ((SEQ=0;SEQ<10;SEQ++));  do
    for  SCRIPT  in  /etc/rc.d/rc${RL}.d/$1${SEQ}*;  do
      if    [  -f  "$SCRIPT"  ]  && 
            [  -x  "$SCRIPT"  ]
      then          $SCRIPT  $2 &
      fi
    done
    wait
  done
}

linear() {
  for ((SEQ=0;SEQ<10;SEQ++));  do
    for  SCRIPT  in  /etc/rc.d/rc${RL}.d/$1${SEQ}*;  do
      if    [  -f  "$SCRIPT"  ]  && 
            [  -x  "$SCRIPT"  ]
      then          $SCRIPT  $2
      fi
    done
    wait
  done
}

ssp() {
  parallelize K stop
  parallelize S start
}

ssl()  {
  linear  K  stop
  linear  S  start
}

export  PATH="/sbin:/bin:/usr/sbin:/usr/bin"
umask   022
 RL=$1
RLL=/var/log/runlevel.$RL.log

case  $RL  in
  3|5|1)   ssl     &>  $RLL &  ;;
    6|0)   ssl                 ;;
    2|4)   ssp |  tee  $RLL    ;;
esac

echo  "$RLL is the runlevel log."
