#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 510
# Required-Start: $local_fs mwavem
# Should-Start: udev
# Required-Stop:  $local_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 6
# Short-Description: mwavemd starts the winmodem
### END INIT INFO

. /lib/lsb/init-functions

only start stop restart try-restart status
server /usr/sbin/mwavem
options /etc/mwavem.conf
