#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 500
# Required-Start: hostname loopback run var_lock_run
# Should-Start: $networks modprobe udev udevsettle
# Required-Stop:  $local_fs
# Should-Stop: kill
# Default-Start: S 1 2 3 4 5
# Default-Stop: 0 6
# Short-Description: dhcpcd configuration of wired and wireless interfaces
### END INIT INFO

if [ "$1" == try-restart ]; then exit 5; fi

. /lib/lsb/init-functions

server	/sbin/auto-network
