#!/bin/sh

start()  {
  echo  -n  "Starting smartd..."
  /usr/sbin/smartd
  echo  "done."
}

stop()  {
  echo  -n  "Stopping smartd..."
  pkill ^smartd 2> /dev/null
}

help()  {
  echo  "Usage:  $0  {start|stop|restart}"
}


case $1 in
    start)                       start  ;;
  restart)  stop  &&  sleep  1;  start  ;;
     stop)  stop                        ;;
        *)  help                        ;;
esac
