#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 510
# Required-Start: $local_fs clamav run
# Required-Stop: $local_fs 
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 6
# Short-Description: clamsmtp scan smtp mails
### END INIT INFO

. /lib/lsb/init-functions

server /usr/sbin/clamsmtpd
