#!/bin/bash

# Copyright 2013 by Kyle Sallee All Rights Reserved
# rgetty acts as a simple getty to run
# login when someone at the keyboard requests it.

clr(){ /bin/deallocvt; printf "%b\033c"; }

greet(){
 clr
 echo "$HOSTNAME"
 [ -f     /etc/issue ] &&
 /bin/cat /etc/issue
}

wait(){
 while greet; ! read -n 1 -t 3600 -p "Press enter for login prompt"; do :; done
 /bin/openvt -- /usr/sbin/rgetty
 greet
}

activate(){
 wait
 exec /bin/login
}

if ! (( $UID == 0 )); then exit 1; fi

trap : SIGHUP SIGINT SIGQUIT SIGILL SIGABRT SIGSTOP
[      -f /usr/libexec/bash/cat ] &&
enable -f /usr/libexec/bash/cat cat
activate
