#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 500
# Required-Start: proc
# Should-Start: udevd udevdsettle modules
# Default-Start: S
# Short-Description: nfsd mounts nfsd on /proc/fs/nfsd
# Description: nfsd mounts nfsd on /proc/fs/nfsd
#	This filesystem needs to be mounted before most
#	NFS daemons, particularly exportfs, mountd, svcgssd, idmapd.
### END INIT INFO

. /lib/lsb/init-functions

NAME=/proc/fs/nfsd
CONF=/etc/exports
OPTS='-n -t nfsd nfsd'

parse "$@"
