#!/bin/bash

### BEGIN INIT INFO
# Provides: var_lib_nfs_rpc_pipefs
# Required-Start: proc var_lib_nfs
# Should-Start:
# Required-Stop: 
# Default-Start: 2 3 4 5
# Default-Stop:
# Short-Description: var_lib_nfs_rpc_pipefs mounts rpc_pipefs on /var/lib/nfs/rpc_pipefs/
### END INIT INFO

. /lib/lsb/init-functions

NAME=/var/lib/nfs/rpc_pipefs
OPTS='-o defaults -t rpc_pipefs rpc_pipefs'

parse "$@"
