#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 710
# Required-Start: $network run
# Required-Stop:  $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: ipropd-master sends database updates to ipropd-slave
### END INIT INFO

. /lib/lsb/init-functions

PIDF=/var/run/ipropd-master.pid
SERV=/usr/libexec/ipropd-master
NAME=ipropd-master
OPTS='--detach'

reload(){
 PIDS="$( pidofproc -p $PIDF $SERV )"
 if   [ -n            "$PIDS" ]
 then kill  -s SIGHUP  $PIDS  &&
      log_success_msg "$NAME configuration reloaded"
 fi
}

parse "$@"
