#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 400
# Required-Start: $network run
# Required-Stop:  $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: kadmind provides server for admin access to database
### END INIT INFO

. /lib/lsb/init-functions

only start stop restart try-restart reload status
pid_file /var/run/kadmind.pid
server /usr/libexec/kadmind
name kadmind

reload(){
 PIDS="$( pidofproc -p $PIDF $SERV )"
 if   [ -n            "$PIDS" ]
 then kill  -s SIGHUP  $PIDS  &&
      log_success_msg "$NAME configuration reload"
 fi
}
