#!/bin/bash

### BEGIN INIT INFO
# Required-Start: dbus run
# Required-Stop:  dbus
# Default-Start: 1 2 3 4 5
# Short-Description: load bluetooth drivers
### END INIT INFO

set -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DESC="Bluetooth subsystem"

HCID_NAME=hcid
HID2HCI_NAME=hid2hci

HCID_EXEC="`which $HCID_NAME || true`"
HID2HCI_EXEC="`which $HID2HCI_NAME || true`"

HCID_ENABLE=true
HID2HCI_ENABLE=true

HCID_CONFIG="/etc/bluetooth/hcid.conf"

[ -e /etc/default/bluetooth ] && . /etc/default/bluetooth

status(){
 echo "$HCID_NAME status:"  ;  hcitool con
 echo "SDP status:"         ;  sdptool browse local
 echo "RFCOMM status:"      ;  rfcomm -a
}

start(){
 echo -n "Starting $DESC:"
 if $HID2HCI_ENABLE && [ -x "$HID2HCI_EXEC" ] ; then
	$HID2HCI_EXEC --tohci > /dev/null 2>&1 || :
	echo -n " $HID2HCI_NAME"
 fi
 if $HCID_ENABLE && [ -x "$HCID_EXEC" -a -f "$HCID_CONFIG" ] ; then
	$HCID_EXEC -s -f $HCID_CONFIG
	echo -n " $HCID_NAME"
 fi
 echo "."
}

stop(){
 echo -n "Stopping $DESC:"
 killall $HCID_NAME > /dev/null 2>&1 || true
 echo -n " $HCID_NAME"
 echo "."
}

help(){
 echo "Usage: $0 {start|stop|restart|status}" >&2
 exit 1
}

parse "$@"
