#!/bin/bash

### BEGIN INIT INFO
# Provides: gui_login
# Required-Start: $network dbus run ICE-unix
# Should-Start: $remote_fs udev xfs dbus
# Required-Stop: kill
# Should-Stop: $remote_fs initramfs
# Default-Start: 4 5
# Default-Stop: 0 6
# Default-Mode: 500
# Short-Description: gdm provides an x11 login.
### END INIT INFO

. /lib/lsb/init-functions

fast
affine
only start stop restart status
server /usr/sbin/gdm-binary
config /etc/gdm/custom.conf
log_file /var/log/gdm.log
domain limited

start(){
 run(){
  [ -d          /var/log/gdm ] ||
  mkdir         /var/log/gdm
  chmod 1770    /var/log/gdm
  chown gdm:gdm /var/log/gdm
  [ -d          /var/gdm ] ||
  mkdir         /var/gdm
  chmod  770    /var/gdm
  chown gdm:gdm /var/gdm
  start_daemon -b -l $LOGF $SERV $OPTS
 }

 if   log_warning_msg "$NAME starting"; run
 then log_success_msg "$NAME started"
 else log_failure_msg "$NAME not started"; status
 fi
}
