#!/bin/bash

### BEGIN INIT INFO
# Required-Start: $local_fs run
# Default-Start: 1 2 3 4 5
# Short-Description: creates directory /var/run/dbus
### END INIT INFO

. /lib/lsb/init-functions

NAME=/var/run/dbus

start(){
 run(){ mkdir -pm 775 $NAME && chown messagebus:messagebus $NAME; }

 if   [ -d $NAME ]; then return; fi
 if   log_warning_msg "$NAME creating"; run
 then log_success_msg "$NAME created"
 else log_failure_msg "$NAME not created"; return 1
 fi
}
       stop(){ :; }
    restart(){ :; }
try_restart(){ :; }
parse "$@"
