#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 510
# Required-Start: $network
# Required-Stop:  $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: updatesrv updates the server
### END INIT INFO

. /lib/lsb/init-functions

only start stop restart status
server /usr/sbin/updatesrv
name updatesrv
