#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 510
# Required-Start: $local_fs $network run
# Should-Start: $remote_fs udev
# Required-Stop: kill
# Should-Stop: $remote_fs
# Default-Start: 4 5
# Default-Stop: 0 6
# Short-Description: provides an X11 font server
### END INIT INFO

. /lib/lsb/init-functions

only start stop restart try-restart status
server /usr/bin/xfs
