#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 710
# Required-Start: $local_fs $network run
# Should-Start: $remote_fs udev
# Required-Stop: kill
# Should-Stop: $remote_fs
# Default-Start: 4 5
# Default-Stop: 0 6
# Short-Description: xfs provides an X11 font server.
### END INIT INFO

. /lib/lsb/init-functions

PIDF=/var/run/xfs.pid
SERV=/usr/bin/X11/xfs

parse "$@"
