#!/bin/bash

### BEGIN INIT INFO
# Default-Mode: 500
# Required-Start: $network run
# Required-Stop:  $network
# Default-Start: S
# Default-Stop: 0 1 6
# Short-Description: creates a logging directory for routing servers.
### END INIT INFO

. /lib/lsb/init-functions

if    ! rootfs; then
 if   [ start == "$1" ]
 then echo "$0 starts only on rootfs" 1>&2; trap - EXIT; exit 1
 else trap - EXIT; exit 0
 fi
fi

only start stop status
server /sbin/zebra
config /etc/quagga/zebra.conf
#domain user
options -d

start(){
 /bin/mkdir -pm 755       /var/log/        /run/
 /bin/mkdir  -m 700       /var/log/quagga/ /run/quagga/
 /bin/chown quagga:quagga /var/log/quagga/ /run/quagga/
}
