#!/bin/bash

### BEGIN INIT INFO
# Provides: msyslog $syslog
# Required-Start: hostname
# Required-Stop: kill
# Default-Start: S
# Default-Stop: 0 6
# Short-Description: msyslog is a replacement for sysklog and syslog
# Description: msyslogd is a near replacement for sysklog, sysklogd and syslog
### END INIT INFO

. /lib/lsb/init-functions

PIDF=/var/run/syslogd.pid
SERV=/usr/sbin/syslogd
NAME="msyslog"

status()  {
  PIDS="$( pidofproc -p $PIDF $SERV )"
  if   [ -n "$PIDS" ]; then log_warning_msg "$NAME is running"; return 0
  elif [ -f "$PIDF" ]; then log_warning_msg "$NAME is dead and $PIDF exists"; return 1
                       else log_warning_msg "$NAME is not running"; return 3
  fi
}

start()  {
  log_warning_msg  "$NAME about to start"
  /bin/cat        /etc/syslog.conf  |
  /usr/bin/tr     ' '  '\n'         |
  /usr/bin/grep   "^/var/log"       |
  /usr/bin/xargs  -l64  touch
  echo  3  >  /proc/sys/kernel/printk
  if    start_daemon     -p $PIDF $SERV -i linux  -i unix
  then  log_success_msg  "$NAME started"
  else  log_failure_msg  "$NAME not started"
        status
  fi
}

stop()  {
  log_warning_msg "$NAME about to stop"
  if    killproc        -p $PIDF -s 15  $SERV
  then  log_success_msg "$NAME stopped"
  else  log_failure_msg "$NAME not stopped"
        status
        return 0
  fi
}

restart() {  stop  &&  sleep  1;  start;  }

try_restart() {
  status  &&  restart
  return 0
}

help()  {
  echo "Usage: $0 {restart|try-restart|force-reload|start|status|stop}" 1>&2
}

case  $1  in
       restart)      restart  ;;
   try-restart)  try_restart  ;;
  force-reload)      restart  ;;
         start)  start        ;;
        status)  status       ;;
          stop)  stop         ;;
             *)  help         ;;
esac
