#!/bin/dash

### BEGIN INIT INFO
# Required-Start: udevd
# Default-Start: S
# Short-Description: udevtrigger turns on dynamic /dev population and module loading
# Description: udevtrigger requests kernel device uevents.
# Coldplug events are used by udevd to popualte /dev
### END INIT INFO

. /lib/lsb/init-functions

if   ! [ -d /etc/dev.old ]
then SERV=/sbin/udevadm; OPTS=trigger; parse "$@"
fi
