#!/bin/bash

### BEGIN INIT INFO
# Provides: udevd udev
# Required-Start: dev-cp sys
# Required-Stop: $local_fs
# Default-Start: S
# Default-Stop: 0 6
# Short-Description: udevd populates /dev
# Description: udevd turns on dynamic /dev population and module loading
### END INIT INFO

. /lib/lsb/init-functions

NAME=udevd
SERV=/sbin/udevd
OPTS='--daemon'

parse "$@"
