#!/bin/bash

### BEGIN INIT INFO
# Provides: ftpsd
# Required-Start: $network
# Required-Stop:  $network
# Default-Start: 3 4 5
# Default-Stop:  0 1 2 6
# Short-Description: ftpsd provides a secure ftp server
# Description:  ftpsd provides a secure ftp server
### END INIT INFO

NAME="bsdftpd-ssl secure ftpd server"
PIDF=/var/run/bsdftpd-ssl.pid
SERV=/usr/sbin/ftpd
PORT=ftps
SECP=secure
TIME=300


start()  {
  log_wraning_msg  "$NAME about to start"
  if    start_daemon  -p $PIDF  \
           $SERV  -D  -l  -T 300  -z $SECP  -P $PORT  -p $PIDF
  then  log_success_msg  "$NAME started"
  else  log_failure_msg  "$NAME not started"
        status
  fi
}


status()  {
  PIDS="$( pidofproc -p $PIDF $SERV )"
  if   [ -n "$PIDS" ]; then log_warning_msg "$NAME is running"; return 0
  elif [ -f "$PIDF" ]; then log_warning_msg "$NAME is dead and $PIDF exists"; return 1
                       else log_warning_msg "$NAME is not running"; return 3
  fi
}

stop()  {
  if    killproc        -p $PIDF -s 15  $SERV
  then  log_success_msg "$NAME stopped"
  else  log_failure_msg "$NAME not stopped"
        status
        return 0
  fi
}

restart()  {  stop  &&  sleep  1;  start;  }

try_restart() {
  status  &&  restart
  return 0
}


help()  {
  echo "Usage: $0 {restart|try-restart|reload|force-reload|start|status|stop}" 1>&2
}


case  $1  in
       restart)      restart  ;;
   try-restart)  try_restart  ;;
        reload)  try_restart  ;;
  force-reload)  try_restart  ;;
         start)  start        ;;
        status)  status       ;;
          stop)  stop         ;;
             *)  help         ;;
esac
